### ISSUE TITLE
owocr started throwing errors again.

### ISSUE THREAD

**Issue by RkSense** [AuroraWright/owocr#7]
![Image](https://github.com/user-attachments/assets/7b464e5f-a2da-4528-bb4b-f51d94a27f77)
on the updated version

**Comment by AuroraWright** [comment]
Should be fixed in 1.9.1 with thanks to https://github.com/dimdenGD/chrome-lens-ocr .
Run `pip install --upgrade owocr` and let me know how it goes.

**Comment by RkSense** [comment]
> Should be fixed in 1.9.1 with thanks to https://github.com/dimdenGD/chrome-lens-ocr . Run `pip install --upgrade owocr` and let me know how it goes.

It works now. Thank you very much!🙏

**Comment by RkSense** [comment]
![Image](https://github.com/user-attachments/assets/96e89e13-6155-4bc1-b0cd-853fc389f70e)
The issue is back for now 😔 @AuroraWright

**Comment by RkSense** [comment]
it is broken again 

![Image](https://github.com/user-attachments/assets/7d0f0c3b-ebd4-441d-bcc8-5120d34f9586)

**Comment by AuroraWright** [comment]
I posted about it here but tl;dr it might be tough this time around unless I'm missing something (which is very possible). I asked a friend for help who's much more knowledgeable than me with web RE https://github.com/dimdenGD/chrome-lens-ocr/issues/29#issuecomment-2758802410
